import React from "react";
import TextField from "@material-ui/core/TextField";
import NavBtns from "./NavBtns";
import { getUniqueId } from "../../../../../../../../hooks/api/trigger";
import ShowAvailableCards from "./ShowAvailableCards";

const isSmall = window.Helper.isSmallScreen();

export default function CardValAndCvv({
    // n1 cvv
    styles,
    handleChange,
    setData,
    setCurrComp,
    data,
    cardVal,
    cardCvv,
    cvvSize,
    setWatermark,
    modalData,
}) {
    const is4Css = cvvSize === 4;

    const showFields = () => (
        <section className="d-flex mx-3 align-items-center justify-content-around">
            <div>
                <p className="text-p font-weight-bold text-normal m-0">
                    MM/AA:
                </p>
                <TextField
                    required
                    margin="dense"
                    onChange={handleChange(setData, data)}
                    error={false}
                    name="cardVal"
                    value={cardVal}
                    variant="outlined"
                    onFocus={() => {
                        isSmall && setWatermark(false);
                    }}
                    type="tel"
                    autoComplete="off"
                    inputProps={{
                        maxLength: 7,
                        style: {
                            ...styles.fieldForm,
                            fontSize: "20px",
                            width: "90px",
                        },
                    }}
                />
            </div>
            <div>
                <p className="text-p font-weight-bold text-normal m-0">CVV:</p>
                <TextField
                    required
                    margin="dense"
                    onChange={handleChange(setData, data)}
                    error={false}
                    name="cardCvv"
                    value={cardCvv}
                    variant="outlined"
                    onFocus={() => {
                        isSmall && setWatermark(false);
                        if (is4Css) return;
                        setData((prev) => ({
                            ...prev,
                            flipCard: getUniqueId(),
                        }));
                    }}
                    onBlur={() => {
                        isSmall && setWatermark(getUniqueId());
                        if (is4Css) return;
                        setData((prev) => ({
                            ...prev,
                            flipCard: getUniqueId(),
                        }));
                    }}
                    type="tel"
                    autoComplete="off"
                    inputProps={{
                        maxLength: cvvSize || 3,
                        style: {
                            ...styles.fieldForm,
                            fontSize: "20px",
                            width: "90px",
                        },
                    }}
                />
            </div>
        </section>
    );

    return (
        <section className="position-relative">
            <p
                className="text-small position-absolute text-p m-0 font-weight-bold"
                style={{ right: "0px" }}
            >
                3/3
            </p>
            {showFields()}
            <NavBtns
                returnCallback={() => setCurrComp("fullName")}
                continueCallback={() => setCurrComp("briefAndValue")}
                continueTitle="ver resumo"
            />
            <ShowAvailableCards modalData={modalData} />
        </section>
    );
}

/*

 */

/*
Card Verification Value
CVV stands for Card Verification Value. This number is vital for completing online transactions and should never be shared with anyone.
The CVV number is generated by debit card issuers (banks or other financial institutions) based on the following details: DEBIT CARD NUMBER.

On am American Express® branded credit or debit card it is a 4 digit numeric code
and this is on the front of the card, not in the back like most branded cards.
 */
